return {
    {
        id = "water",
        basePotionId = nil,
        potion = "minecraft:water",
        displayName = "Water Bottle",
        splash = false,
        ingredient = nil,
        potionType = "normal",
        nbt = "8286054c65764b60b7ecf42985b29fbe",
    },
    {
        id = "water_lingering",
        basePotionId = "water",
        potion = "minecraft:water",
        splash = false,
        ingredient = "minecraft:dragon_breath",
        potionType = "lingering",
        nbt = "8286054c65764b60b7ecf42985b29fbe",
    },
    {
        id = "mundane",
        basePotionId = "water",
        potion = "minecraft:mundane",
        displayName = "Mundane Potion",
        splash = false,
        ingredient = "minecraft:sugar",
        potionType = "normal",
        nbt = "f95eee7dd5304c9ab0d3d5e6e6f31bbb",
    },
    {
        id = "thick",
        basePotionId = "water",
        potion = "minecraft:thick",
        displayName = "Thick Potion",
        splash = false,
        ingredient = "minecraft:glowstone_dust",
        potionType = "normal",
        nbt = "fe9a7784db719dd4ce76a7d98ccafabd",
    },
    {
        id = "awkward",
        basePotionId = "water",
        potion = "minecraft:awkward",
        displayName = "Awkward Potion",
        splash = false,
        ingredient = "minecraft:nether_wart",
        potionType = "normal",
        nbt = "7f0aae7befcab8b4190cc6db04dc116a",
    },
    {
        id = "night_vision",
        basePotionId = "awkward",
        potion = "minecraft:night_vision",
        displayName = "Night Vision",
        splash = false,
        ingredient = "minecraft:golden_carrot",
        potionType = "normal",
        nbt = "7b927966e9fb8bf63707e047d1115bf6",
    },
    {
        id = "long_night_vision",
        basePotionId = "night_vision",
        potion = "minecraft:long_night_vision",
        displayName = "Night Vision+",
        splash = false,
        ingredient = "minecraft:redstone",
        potionType = "normal",
        nbt = "49e637ce643534edf76760276a256f83",
    },
    {
        id = "invisibility",
        basePotionId = "night_vision",
        potion = "minecraft:invisibility",
        displayName = "Invisibility",
        splash = false,
        ingredient = "minecraft:fermented_spider_eye",
        potionType = "normal",
        nbt = "4819bff5a3ef5729b80b029db4197d1e",
    },
    {
        id = "long_invisibility",
        basePotionId = "invisibility",
        potion = "minecraft:long_invisibility",
        displayName = "Invisibility+",
        splash = false,
        ingredient = "minecraft:redstone",
        potionType = "normal",
        nbt = "c0ababf814d554fdaf18666f4af13a59",
    },
    {
        id = "leaping",
        basePotionId = "awkward",
        potion = "minecraft:leaping",
        displayName = "Leaping",
        splash = false,
        ingredient = "minecraft:rabbit_foot",
        potionType = "normal",
        nbt = "23a2e7a760bef7f699b61346d102e27d",
    },
    {
        id = "long_leaping",
        basePotionId = "leaping",
        potion = "minecraft:long_leaping",
        displayName = "Leaping+",
        splash = false,
        ingredient = "minecraft:redstone",
        potionType = "normal",
        nbt = "11511284100f60397b173cbc5170411b",
    },
    {
        id = "long_leaping",
        basePotionId = "leaping",
        potion = "minecraft:strong_leaping",
        displayName = "Leaping II",
        splash = false,
        ingredient = "minecraft:glowstone_dust",
        potionType = "normal",
        nbt = "8b633c4bc7b7593e77b4b40017d17deb",
    },
    {
        basePotionId = "awkward",
        potion = "minecraft:fire_resistance",
        displayName = "Fire Resistance",
        splash = false,
        ingredient = "minecraft:magma_cream",
        potionType = "normal",
        nbt = "4c2bc6cbe1e099ed20b9b46aca691ff0",
    },
    {
        basePotionId = "4c2bc6cbe1e099ed20b9b46aca691ff0",
        potion = "minecraft:long_fire_resistance",
        displayName = "Fire Resistance+",
        splash = false,
        ingredient = "minecraft:redstone",
        potionType = "normal",
        nbt = "52c71f193bdd6ca60eb1a38ea256d6bc",
    },
    {
        basePotionId = "awkward",
        potion = "minecraft:swiftness",
        displayName = "Swiftness",
        splash = false,
        ingredient = "minecraft:sugar",
        potionType = "normal",
        nbt = "f9cca098e635cfaaf82752b4bf83323c",
    },
    {
        basePotionId = "f9cca098e635cfaaf82752b4bf83323c",
        potion = "minecraft:long_swiftness",
        displayName = "Swiftness+",
        splash = false,
        ingredient = "minecraft:redstone",
        potionType = "normal",
        nbt = "b52612c4159f570ecc4e89a69e5d69d6",
    },
    {
        basePotionId = "f9cca098e635cfaaf82752b4bf83323c",
        potion = "minecraft:strong_swiftness",
        displayName = "Swiftness II",
        splash = false,
        ingredient = "minecraft:glowstone_dust",
        potionType = "normal",
        nbt = "53463ce0188ef51518efa21503c0b78f",
    },
    {
        basePotionId = "f9cca098e635cfaaf82752b4bf83323c",
        potion = "minecraft:slowness",
        displayName = "Slowness",
        splash = false,
        ingredient = "minecraft:fermented_spider_eye",
        potionType = "normal",
        nbt = "e281fdf176331217c01f59aef8110bb3",
    },
    {
        basePotionId = "e281fdf176331217c01f59aef8110bb3",
        potion = "minecraft:long_slowness",
        displayName = "Slowness+",
        splash = false,
        ingredient = "minecraft:redstone",
        potionType = "normal",
        nbt = "fe685eb987eb3cb37a6ebad125534d80",
    },
    {
        basePotionId = "e281fdf176331217c01f59aef8110bb3",
        potion = "minecraft:strong_slowness",
        displayName = "Slowness IV",
        splash = false,
        ingredient = "minecraft:glowstone_dust",
        potionType = "normal",
        nbt = "4fa963fabd6aa5b93dea50ebf19911f6",
    },
    {
        basePotionId = "awkward",
        potion = "minecraft:turtle_master",
        displayName = "Turtle Master",
        splash = false,
        ingredient = "minecraft:turtle_helmet",
        potionType = "normal",
        nbt = "d14bb0906ba67c76e8d3a1a6b9bdb993",
    },
    {
        basePotionId = "d14bb0906ba67c76e8d3a1a6b9bdb993",
        potion = "minecraft:long_turtle_master",
        displayName = "Turtle Master+",
        splash = false,
        ingredient = "minecraft:redstone",
        potionType = "normal",
        nbt = "a9bb9b2a58970cd2fc9db7e13b0b4f3b",
    },
    {
        basePotionId = "d14bb0906ba67c76e8d3a1a6b9bdb993",
        potion = "minecraft:strong_turtle_master",
        displayName = "Turtle Master II",
        splash = false,
        ingredient = "minecraft:glowstone_dust",
        potionType = "normal",
        nbt = "312db0d27bebe67a3084cbcff45c56cd",
    },
    {
        basePotionId = "awkward",
        potion = "minecraft:water_breathing",
        displayName = "Water Breathing",
        splash = false,
        ingredient = "minecraft:pufferfish",
        potionType = "normal",
        nbt = "6c1d0ec5fc6a54cb022e30f3f03f42ac",
    },
    {
        basePotionId = "6c1d0ec5fc6a54cb022e30f3f03f42ac",
        potion = "minecraft:long_water_breathing",
        displayName = "Water Breathing+",
        splash = false,
        ingredient = "minecraft:redstone",
        potionType = "normal",
        nbt = "d30903bfd13f49021b058083866d333a",
    },
    {
        basePotionId = "awkward",
        potion = "minecraft:healing",
        displayName = "Healing",
        splash = false,
        ingredient = "minecraft:glistering_melon_slice",
        potionType = "normal",
        nbt = "d3b61c763509f56de2ceaa009b5d614b",
    },
    {
        basePotionId = "d3b61c763509f56de2ceaa009b5d614b",
        potion = "minecraft:strong_healing",
        displayName = "Healing II",
        splash = false,
        ingredient = "minecraft:glowstone_dust",
        potionType = "normal",
        nbt = "d2821522a06dc3a77780b3341bb9cd0d",
    },
    {
        basePotionId = "01f6a8923f5cd0440d6d4a1404000bdc",
        potion = "minecraft:harming",
        displayName = "Harming",
        splash = false,
        ingredient = "minecraft:fermented_spider_eye",
        potionType = "normal",
        nbt = "d15b871490c1653f5d18c25753bc0f64",
    },
    {
        basePotionId = "d15b871490c1653f5d18c25753bc0f64",
        potion = "minecraft:strong_harming",
        displayName = "Harming II",
        splash = false,
        ingredient = "minecraft:glowstone_dust",
        potionType = "normal",
        nbt = "7002fcb7eee67990425c3e2acbc92a26",
    },
    {
        basePotionId = "awkward",
        potion = "minecraft:poison",
        displayName = "Poison",
        splash = false,
        ingredient = "minecraft:spider_eye",
        potionType = "normal",
        nbt = "01f6a8923f5cd0440d6d4a1404000bdc",
    },
    {
        basePotionId = "01f6a8923f5cd0440d6d4a1404000bdc",
        potion = "minecraft:long_poison",
        displayName = "Poison+",
        splash = false,
        ingredient = "minecraft:redstone",
        potionType = "normal",
        nbt = "347700b83a7f5fdc7f32a1821b1c3c64",
    },
    {
        basePotionId = "01f6a8923f5cd0440d6d4a1404000bdc",
        potion = "minecraft:strong_poison",
        displayName = "Poison II",
        splash = false,
        ingredient = "minecraft:glowstone_dust",
        potionType = "normal",
        nbt = "a6d61c05747fd050044d936af6a65484",
    },
    {
        basePotionId = "awkward",
        potion = "minecraft:regeneration",
        displayName = "Regeneration",
        splash = false,
        ingredient = "minecraft:ghast_tear",
        potionType = "normal",
        nbt = "0c284bac973ce3d74a033d26e97fb4e2",
    },
    {
        basePotionId = "0c284bac973ce3d74a033d26e97fb4e2",
        potion = "minecraft:long_regeneration",
        displayName = "Regeneration+",
        splash = false,
        ingredient = "minecraft:redstone",
        potionType = "normal",
        nbt = "750f67c4e04540dd376d65de258cf83a",
    },
    {
        basePotionId = "0c284bac973ce3d74a033d26e97fb4e2",
        potion = "minecraft:strong_regeneration",
        displayName = "Regeneration II",
        splash = false,
        ingredient = "minecraft:glowstone_dust",
        potionType = "normal",
        nbt = "dd185b385cb1a0bf44aa319217d21944",
    },
    {
        basePotionId = "awkward",
        potion = "minecraft:strength",
        displayName = "Strength",
        splash = false,
        ingredient = "minecraft:blaze_powder",
        potionType = "normal",
        nbt = "03d2a4a1b8486408a6a69ad3af8cc4d5",
    },
    {
        basePotionId = "03d2a4a1b8486408a6a69ad3af8cc4d5",
        potion = "minecraft:long_strength",
        displayName = "Strength+",
        splash = false,
        ingredient = "minecraft:redstone",
        potionType = "normal",
        nbt = "651dcaa96623a1fe39bceb700adb3833",
    },
    {
        basePotionId = "03d2a4a1b8486408a6a69ad3af8cc4d5",
        potion = "minecraft:strong_strength",
        displayName = "Strength II",
        splash = false,
        ingredient = "minecraft:glowstone_dust",
        potionType = "normal",
        nbt = "b51df730a552d6f5f6b0707b9e4a92ab",
    },
    {
        basePotionId = "water",
        potion = "minecraft:weakness",
        displayName = "Weakness",
        splash = false,
        ingredient = "minecraft:fermented_spider_eye",
        potionType = "normal",
        nbt = "a2639fdeb17a5487f66606d115c1862a",
    },
    {
        basePotionId = "a2639fdeb17a5487f66606d115c1862a",
        potion = "minecraft:long_weakness",
        displayName = "Weakness+",
        splash = false,
        ingredient = "minecraft:redstone_dust",
        potionType = "normal",
        nbt = "578a27ac719ffc69d5288d97a366fb8e",
    },
    {
        basePotionId = "awkward",
        potion = "minecraft:slow_falling",
        displayName = "Slow Falling",
        splash = false,
        ingredient = "minecraft:phantom_membrane",
        potionType = "normal",
        nbt = "108b859a0bacaae84dc3dc3b5700e9d0",
    },
    {
        basePotionId = "108b859a0bacaae84dc3dc3b5700e9d0",
        potion = "minecraft:long_slow_falling",
        displayName = "Slow Falling+",
        splash = false,
        ingredient = "minecraft:redstone",
        potionType = "normal",
        nbt = "03a9d99bdf9566cac249289476e7cfcc",
    },
    {
        id = "water_splash",
        basePotionId = "water",
        potion = "minecraft:water",
        splash = true,
        ingredient = "minecraft:gunpowder",
        potionType = "splash",
        nbt = "8286054c65764b60b7ecf42985b29fbe",
    },
    {
        id = "mundane_splash",
        basePotionId = "f95eee7dd5304c9ab0d3d5e6e6f31bbb",
        potion = "minecraft:mundane",
        displayName = "Mundane Potion",
        splash = true,
        ingredient = "minecraft:gunpowder",
        potionType = "splash",
        nbt = "f95eee7dd5304c9ab0d3d5e6e6f31bbb",
    },
    {
        id = "thick_splash",
        basePotionId = "fe9a7784db719dd4ce76a7d98ccafabd",
        potion = "minecraft:thick",
        splash = true,
        ingredient = "minecraft:gunpowder",
        potionType = "splash",
        nbt = "fe9a7784db719dd4ce76a7d98ccafabd",
    },
    {
        basePotionId = "awkward",
        potion = "minecraft:awkward",
        splash = true,
        ingredient = "minecraft:gunpowder",
        potionType = "splash",
        nbt = "7f0aae7befcab8b4190cc6db04dc116a",
    },
    {
        id = "night_vision_splash",
        basePotionId = "night_vision",
        potion = "minecraft:night_vision",
        displayName = "Night Vision",
        splash = true,
        ingredient = "minecraft:gunpowder",
        potionType = "splash",
        nbt = "7b927966e9fb8bf63707e047d1115bf6",
    },
    {
        basePotionId = "",
        potion = "minecraft:long_night_vision",
        splash = true,
        ingredient = "",
        potionType = "splash",
        nbt = "49e637ce643534edf76760276a256f83",
    },
    {
        basePotionId = "",
        potion = "minecraft:invisibility",
        splash = true,
        ingredient = "",
        potionType = "splash",
        nbt = "4819bff5a3ef5729b80b029db4197d1e",
    },
    {
        basePotionId = "",
        potion = "minecraft:long_invisibility",
        splash = true,
        ingredient = "",
        potionType = "splash",
        nbt = "c0ababf814d554fdaf18666f4af13a59",
    },
    {
        basePotionId = "",
        potion = "minecraft:leaping",
        splash = true,
        ingredient = "",
        potionType = "splash",
        nbt = "23a2e7a760bef7f699b61346d102e27d",
    },
    {
        basePotionId = "",
        potion = "minecraft:long_leaping",
        splash = true,
        ingredient = "",
        potionType = "splash",
        nbt = "11511284100f60397b173cbc5170411b",
    },
    {
        basePotionId = "",
        potion = "minecraft:strong_leaping",
        splash = true,
        ingredient = "",
        potionType = "splash",
        nbt = "8b633c4bc7b7593e77b4b40017d17deb",
    },
    {
        basePotionId = "",
        potion = "minecraft:fire_resistance",
        splash = true,
        ingredient = "",
        potionType = "splash",
        nbt = "4c2bc6cbe1e099ed20b9b46aca691ff0",
    },
    {
        basePotionId = "",
        potion = "minecraft:long_fire_resistance",
        splash = true,
        ingredient = "",
        potionType = "splash",
        nbt = "52c71f193bdd6ca60eb1a38ea256d6bc",
    },
    {
        basePotionId = "",
        potion = "minecraft:swiftness",
        splash = true,
        ingredient = "",
        potionType = "splash",
        nbt = "f9cca098e635cfaaf82752b4bf83323c",
    },
    {
        basePotionId = "",
        potion = "minecraft:long_swiftness",
        splash = true,
        ingredient = "",
        potionType = "splash",
        nbt = "b52612c4159f570ecc4e89a69e5d69d6",
    },
    {
        basePotionId = "",
        potion = "minecraft:strong_swiftness",
        splash = true,
        ingredient = "",
        potionType = "splash",
        nbt = "53463ce0188ef51518efa21503c0b78f",
    },
    {
        basePotionId = "",
        potion = "minecraft:slowness",
        splash = true,
        ingredient = "",
        potionType = "splash",
        nbt = "e281fdf176331217c01f59aef8110bb3",
    },
    {
        basePotionId = "",
        potion = "minecraft:long_slowness",
        splash = true,
        ingredient = "",
        potionType = "splash",
        nbt = "fe685eb987eb3cb37a6ebad125534d80",
    },
    {
        basePotionId = "",
        potion = "minecraft:strong_slowness",
        splash = true,
        ingredient = "",
        potionType = "splash",
        nbt = "4fa963fabd6aa5b93dea50ebf19911f6",
    },
    {
        basePotionId = "",
        potion = "minecraft:turtle_master",
        splash = true,
        ingredient = "",
        potionType = "splash",
        nbt = "d14bb0906ba67c76e8d3a1a6b9bdb993",
    },
    {
        basePotionId = "",
        potion = "minecraft:long_turtle_master",
        splash = true,
        ingredient = "",
        potionType = "splash",
        nbt = "a9bb9b2a58970cd2fc9db7e13b0b4f3b",
    },
    {
        basePotionId = "",
        potion = "minecraft:strong_turtle_master",
        splash = true,
        ingredient = "",
        potionType = "splash",
        nbt = "312db0d27bebe67a3084cbcff45c56cd",
    },
    {
        basePotionId = "",
        potion = "minecraft:water_breathing",
        splash = true,
        ingredient = "",
        potionType = "splash",
        nbt = "6c1d0ec5fc6a54cb022e30f3f03f42ac",
    },
    {
        basePotionId = "",
        potion = "minecraft:long_water_breathing",
        splash = true,
        ingredient = "",
        potionType = "splash",
        nbt = "d30903bfd13f49021b058083866d333a",
    },
    {
        basePotionId = "",
        potion = "minecraft:healing",
        splash = true,
        ingredient = "",
        potionType = "splash",
        nbt = "d3b61c763509f56de2ceaa009b5d614b",
    },
    {
        basePotionId = "",
        potion = "minecraft:strong_healing",
        splash = true,
        ingredient = "",
        potionType = "splash",
        nbt = "d2821522a06dc3a77780b3341bb9cd0d",
    },
    {
        basePotionId = "",
        potion = "minecraft:harming",
        splash = true,
        ingredient = "",
        potionType = "splash",
        nbt = "d15b871490c1653f5d18c25753bc0f64",
    },
    {
        basePotionId = "",
        potion = "minecraft:strong_harming",
        splash = true,
        ingredient = "",
        potionType = "splash",
        nbt = "7002fcb7eee67990425c3e2acbc92a26",
    },
    {
        basePotionId = "",
        potion = "minecraft:poison",
        splash = true,
        ingredient = "",
        potionType = "splash",
        nbt = "01f6a8923f5cd0440d6d4a1404000bdc",
    },
    {
        basePotionId = "",
        potion = "minecraft:long_poison",
        splash = true,
        ingredient = "",
        potionType = "splash",
        nbt = "347700b83a7f5fdc7f32a1821b1c3c64",
    },
    {
        basePotionId = "",
        potion = "minecraft:strong_poison",
        splash = true,
        ingredient = "",
        potionType = "splash",
        nbt = "a6d61c05747fd050044d936af6a65484",
    },
    {
        basePotionId = "",
        potion = "minecraft:regeneration",
        splash = true,
        ingredient = "",
        potionType = "splash",
        nbt = "0c284bac973ce3d74a033d26e97fb4e2",
    },
    {
        basePotionId = "",
        potion = "minecraft:long_regeneration",
        splash = true,
        ingredient = "",
        potionType = "splash",
        nbt = "750f67c4e04540dd376d65de258cf83a",
    },
    {
        basePotionId = "",
        potion = "minecraft:strong_regeneration",
        splash = true,
        ingredient = "",
        potionType = "splash",
        nbt = "dd185b385cb1a0bf44aa319217d21944",
    },
    {
        basePotionId = "",
        potion = "minecraft:strength",
        splash = true,
        ingredient = "",
        potionType = "splash",
        nbt = "03d2a4a1b8486408a6a69ad3af8cc4d5",
    },
    {
        basePotionId = "",
        potion = "minecraft:long_strength",
        splash = true,
        ingredient = "",
        potionType = "splash",
        nbt = "651dcaa96623a1fe39bceb700adb3833",
    },
    {
        basePotionId = "",
        potion = "minecraft:strong_strength",
        splash = true,
        ingredient = "",
        potionType = "splash",
        nbt = "b51df730a552d6f5f6b0707b9e4a92ab",
    },
    {
        basePotionId = "",
        potion = "minecraft:weakness",
        splash = true,
        ingredient = "",
        potionType = "splash",
        nbt = "a2639fdeb17a5487f66606d115c1862a",
    },
    {
        basePotionId = "",
        potion = "minecraft:long_weakness",
        splash = true,
        ingredient = "",
        potionType = "splash",
        nbt = "578a27ac719ffc69d5288d97a366fb8e",
    },
    {
        basePotionId = "",
        potion = "minecraft:luck",
        splash = true,
        ingredient = "",
        potionType = "splash",
        nbt = "9362997b13c9a0689854e731fe098ee9",
    },
    {
        basePotionId = "",
        potion = "minecraft:slow_falling",
        splash = true,
        ingredient = "",
        potionType = "splash",
        nbt = "108b859a0bacaae84dc3dc3b5700e9d0",
    },
    {
        basePotionId = "",
        potion = "minecraft:long_slow_falling",
        splash = true,
        ingredient = "",
        potionType = "splash",
        nbt = "03a9d99bdf9566cac249289476e7cfcc",
    },
    {
        basePotionId = "",
        potion = "minecraft:mundane",
        splash = false,
        ingredient = "minecraft:dragon_breath",
        potionType = "lingering",
        nbt = "f95eee7dd5304c9ab0d3d5e6e6f31bbb",
    },
    {
        basePotionId = "",
        potion = "minecraft:thick",
        splash = false,
        ingredient = "minecraft:dragon_breath",
        potionType = "lingering",
        nbt = "fe9a7784db719dd4ce76a7d98ccafabd",
    },
    {
        basePotionId = "",
        potion = "minecraft:awkward",
        splash = false,
        ingredient = "minecraft:dragon_breath",
        potionType = "lingering",
        nbt = "7f0aae7befcab8b4190cc6db04dc116a",
    },
    {
        basePotionId = "",
        potion = "minecraft:night_vision",
        splash = false,
        ingredient = "minecraft:dragon_breath",
        potionType = "lingering",
        nbt = "7b927966e9fb8bf63707e047d1115bf6",
    },
    {
        basePotionId = "",
        potion = "minecraft:long_night_vision",
        splash = false,
        ingredient = "minecraft:dragon_breath",
        potionType = "lingering",
        nbt = "49e637ce643534edf76760276a256f83",
    },
    {
        basePotionId = "",
        potion = "minecraft:invisibility",
        splash = false,
        ingredient = "minecraft:dragon_breath",
        potionType = "lingering",
        nbt = "4819bff5a3ef5729b80b029db4197d1e",
    },
    {
        basePotionId = "",
        potion = "minecraft:long_invisibility",
        splash = false,
        ingredient = "minecraft:dragon_breath",
        potionType = "lingering",
        nbt = "c0ababf814d554fdaf18666f4af13a59",
    },
    {
        basePotionId = "",
        potion = "minecraft:leaping",
        splash = false,
        ingredient = "minecraft:dragon_breath",
        potionType = "lingering",
        nbt = "23a2e7a760bef7f699b61346d102e27d",
    },
    {
        basePotionId = "",
        potion = "minecraft:long_leaping",
        splash = false,
        ingredient = "minecraft:dragon_breath",
        potionType = "lingering",
        nbt = "11511284100f60397b173cbc5170411b",
    },
    {
        basePotionId = "",
        potion = "minecraft:strong_leaping",
        splash = false,
        ingredient = "minecraft:dragon_breath",
        potionType = "lingering",
        nbt = "8b633c4bc7b7593e77b4b40017d17deb",
    },
    {
        basePotionId = "",
        potion = "minecraft:fire_resistance",
        splash = false,
        ingredient = "minecraft:dragon_breath",
        potionType = "lingering",
        nbt = "4c2bc6cbe1e099ed20b9b46aca691ff0",
    },
    {
        basePotionId = "",
        potion = "minecraft:long_fire_resistance",
        splash = false,
        ingredient = "minecraft:dragon_breath",
        potionType = "lingering",
        nbt = "52c71f193bdd6ca60eb1a38ea256d6bc",
    },
    {
        basePotionId = "",
        potion = "minecraft:swiftness",
        splash = false,
        ingredient = "minecraft:dragon_breath",
        potionType = "lingering",
        nbt = "f9cca098e635cfaaf82752b4bf83323c",
    },
    {
        basePotionId = "",
        potion = "minecraft:long_swiftness",
        splash = false,
        ingredient = "minecraft:dragon_breath",
        potionType = "lingering",
        nbt = "b52612c4159f570ecc4e89a69e5d69d6",
    },
    {
        basePotionId = "",
        potion = "minecraft:strong_swiftness",
        splash = false,
        ingredient = "minecraft:dragon_breath",
        potionType = "lingering",
        nbt = "53463ce0188ef51518efa21503c0b78f",
    },
    {
        basePotionId = "",
        potion = "minecraft:slowness",
        splash = false,
        ingredient = "minecraft:dragon_breath",
        potionType = "lingering",
        nbt = "e281fdf176331217c01f59aef8110bb3",
    },
    {
        basePotionId = "",
        potion = "minecraft:long_slowness",
        splash = false,
        ingredient = "minecraft:dragon_breath",
        potionType = "lingering",
        nbt = "fe685eb987eb3cb37a6ebad125534d80",
    },
    {
        basePotionId = "",
        potion = "minecraft:strong_slowness",
        splash = false,
        ingredient = "minecraft:dragon_breath",
        potionType = "lingering",
        nbt = "4fa963fabd6aa5b93dea50ebf19911f6",
    },
    {
        basePotionId = "",
        potion = "minecraft:turtle_master",
        splash = false,
        ingredient = "minecraft:dragon_breath",
        potionType = "lingering",
        nbt = "d14bb0906ba67c76e8d3a1a6b9bdb993",
    },
    {
        basePotionId = "",
        potion = "minecraft:long_turtle_master",
        splash = false,
        ingredient = "minecraft:dragon_breath",
        potionType = "lingering",
        nbt = "a9bb9b2a58970cd2fc9db7e13b0b4f3b",
    },
    {
        basePotionId = "",
        potion = "minecraft:strong_turtle_master",
        splash = false,
        ingredient = "minecraft:dragon_breath",
        potionType = "lingering",
        nbt = "312db0d27bebe67a3084cbcff45c56cd",
    },
    {
        basePotionId = "",
        potion = "minecraft:water_breathing",
        splash = false,
        ingredient = "minecraft:dragon_breath",
        potionType = "lingering",
        nbt = "6c1d0ec5fc6a54cb022e30f3f03f42ac",
    },
    {
        basePotionId = "",
        potion = "minecraft:long_water_breathing",
        splash = false,
        ingredient = "minecraft:dragon_breath",
        potionType = "lingering",
        nbt = "d30903bfd13f49021b058083866d333a",
    },
    {
        basePotionId = "",
        potion = "minecraft:healing",
        splash = false,
        ingredient = "minecraft:dragon_breath",
        potionType = "lingering",
        nbt = "d3b61c763509f56de2ceaa009b5d614b",
    },
    {
        basePotionId = "",
        potion = "minecraft:strong_healing",
        splash = false,
        ingredient = "minecraft:dragon_breath",
        potionType = "lingering",
        nbt = "d2821522a06dc3a77780b3341bb9cd0d",
    },
    {
        basePotionId = "",
        potion = "minecraft:harming",
        splash = false,
        ingredient = "minecraft:dragon_breath",
        potionType = "lingering",
        nbt = "d15b871490c1653f5d18c25753bc0f64",
    },
    {
        basePotionId = "",
        potion = "minecraft:strong_harming",
        splash = false,
        ingredient = "minecraft:dragon_breath",
        potionType = "lingering",
        nbt = "7002fcb7eee67990425c3e2acbc92a26",
    },
    {
        basePotionId = "",
        potion = "minecraft:poison",
        splash = false,
        ingredient = "minecraft:dragon_breath",
        potionType = "lingering",
        nbt = "01f6a8923f5cd0440d6d4a1404000bdc",
    },
    {
        basePotionId = "",
        potion = "minecraft:long_poison",
        splash = false,
        ingredient = "minecraft:dragon_breath",
        potionType = "lingering",
        nbt = "347700b83a7f5fdc7f32a1821b1c3c64",
    },
    {
        basePotionId = "",
        potion = "minecraft:strong_poison",
        splash = false,
        ingredient = "minecraft:dragon_breath",
        potionType = "lingering",
        nbt = "a6d61c05747fd050044d936af6a65484",
    },
    {
        basePotionId = "",
        potion = "minecraft:regeneration",
        splash = false,
        ingredient = "minecraft:dragon_breath",
        potionType = "lingering",
        nbt = "0c284bac973ce3d74a033d26e97fb4e2",
    },
    {
        basePotionId = "",
        potion = "minecraft:long_regeneration",
        splash = false,
        ingredient = "minecraft:dragon_breath",
        potionType = "lingering",
        nbt = "750f67c4e04540dd376d65de258cf83a",
    },
    {
        basePotionId = "",
        potion = "minecraft:strong_regeneration",
        splash = false,
        ingredient = "minecraft:dragon_breath",
        potionType = "lingering",
        nbt = "dd185b385cb1a0bf44aa319217d21944",
    },
    {
        basePotionId = "",
        potion = "minecraft:strength",
        splash = false,
        ingredient = "minecraft:dragon_breath",
        potionType = "lingering",
        nbt = "03d2a4a1b8486408a6a69ad3af8cc4d5",
    },
    {
        basePotionId = "",
        potion = "minecraft:long_strength",
        splash = false,
        ingredient = "minecraft:dragon_breath",
        potionType = "lingering",
        nbt = "651dcaa96623a1fe39bceb700adb3833",
    },
    {
        basePotionId = "",
        potion = "minecraft:strong_strength",
        splash = false,
        ingredient = "minecraft:dragon_breath",
        potionType = "lingering",
        nbt = "b51df730a552d6f5f6b0707b9e4a92ab",
    },
    {
        basePotionId = "",
        potion = "minecraft:weakness",
        splash = false,
        ingredient = "minecraft:dragon_breath",
        potionType = "lingering",
        nbt = "a2639fdeb17a5487f66606d115c1862a",
    },
    {
        basePotionId = "",
        potion = "minecraft:long_weakness",
        splash = false,
        ingredient = "minecraft:dragon_breath",
        potionType = "lingering",
        nbt = "578a27ac719ffc69d5288d97a366fb8e",
    },
    {
        basePotionId = "",
        potion = "minecraft:luck",
        splash = false,
        ingredient = "minecraft:dragon_breath",
        potionType = "lingering",
        nbt = "9362997b13c9a0689854e731fe098ee9",
    },
    {
        basePotionId = "",
        potion = "minecraft:slow_falling",
        splash = false,
        ingredient = "minecraft:dragon_breath",
        potionType = "lingering",
        nbt = "108b859a0bacaae84dc3dc3b5700e9d0",
    },
    {
        basePotionId = "",
        potion = "minecraft:long_slow_falling",
        splash = false,
        ingredient = "minecraft:dragon_breath",
        potionType = "lingering",
        nbt = "03a9d99bdf9566cac249289476e7cfcc",
    },
}
